[boris]
  version = 1

[build.dist-7-10]
  git = "refs/heads/master"

[build.branches-7-10]
  git = "refs/heads/topic/*"

[build.validate]
  git = "refs/heads/master"

[build.submodules]
  git = "refs/heads/master"

[build.submodules-branches]
  git = "refs/heads/topic/*"

[build.rebased]
  git = "refs/heads/master"
